version: '3'
services:
  db:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todosvr
      TZ: Asia/Tokyo
    volumes:
      - ./mysql_data:/var/lib/mysql
  web:
    build:
      context: .
      args:
        UID: $UID
        GID: $GID
        UNAME: $UNAME
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      HOST: $HOST
    volumes:
      - ./src:/src
      - ./bundle:/usr/local/bundle
    ports:
      - "${RAILS_PORT}:3000"
    user: "${UID}:${GID}"
    tty: true
    stdin_open: true
    depends_on:
      - db
